# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-22 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arp_ent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cl_address', models.CharField(max_length=100)),
                ('mac', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Arp_ent',
            },
        ),
        migrations.CreateModel(
            name='Auth_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc_file', models.CharField(max_length=50)),
                ('cl_address', models.CharField(max_length=50)),
                ('mac', models.CharField(max_length=17)),
                ('ip_add', models.CharField(max_length=15)),
                ('kl_service', models.CharField(max_length=1)),
                ('downl', models.CharField(max_length=6)),
                ('upl', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'LAN_Sosnowiec_klienci',
            },
        ),
        migrations.CreateModel(
            name='Client_rec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc_file', models.CharField(max_length=50)),
                ('ln_nr', models.IntegerField()),
                ('cl_address', models.CharField(max_length=50)),
                ('mac', models.CharField(max_length=17)),
                ('ip_add', models.CharField(max_length=15)),
                ('kl_service', models.CharField(max_length=1)),
                ('downl', models.CharField(max_length=6)),
                ('upl', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'LAN_server_clients',
            },
        ),
    ]
